## Visualisation 3 :  Time

In [21]:
import altair as alt
import pandas as pd
import geopandas as gpd # Requires geopandas -- e.g.: conda install -c conda-forge geopandas
alt.data_transformers.enable('json') # Let Altair/Vega-Lite work with large data sets

pass

In [22]:
names = pd.read_csv("../data/dpt2020.csv", sep=";")
names.drop(names[names.preusuel == '_PRENOMS_RARES'].index, inplace=True)
names.drop(names[names.dpt == 'XX'].index, inplace=True)

names.sample(5)

         sexe   preusuel annais  dpt  nombre
3576062     2      SONIA   1956   60       3
1985991     2    AURÉLIE   2009  972       3
2019549     2  BERNADINE   1931  971       4
810805      1   JEAN-LUC   1965   30      33
196845      1      AYMAN   2013   94       9

In [23]:
depts = gpd.read_file('../data/departements-version-simplifiee.geojson')

depts.sample(5)

   code               nom                                           geometry
79   79       Deux-Sèvres  POLYGON ((-0.89196 46.97582, -0.85592 46.97908...
73   73            Savoie  POLYGON ((6.80252 45.77837, 6.80842 45.72515, ...
44   44  Loire-Atlantique  POLYGON ((-2.45849 47.44812, -2.45343 47.46207...
45   45            Loiret  POLYGON ((2.93631 48.16339, 2.97126 48.15183, ...
27   29         Finistère  MULTIPOLYGON (((-5.1026 48.43612, -5.1036 48.4...

In [24]:
# Keep a reference around to the plain pandas dataframe, without geometry data, just in case
just_names = names

names = depts.merge(names, how='right', left_on='code', right_on='dpt')

names.sample(5)

,code,nom,geometry,sexe,preusuel,annais,dpt,nombre
1873626,44,Loire-Atlantique,"POLYGON ((-2.45849 47.44812, -2.45343 47.46207...",2,ANNE-CLAIRE,1977,44,11
2925281,76,Seine-Maritime,"POLYGON ((1.38155 50.06577, 1.40926 50.05707, ...",2,MAELISS,2002,76,3
1961900,88,Vosges,"POLYGON ((5.47006 48.42093, 5.51099 48.41822, ...",2,BÉATRICE,1958,88,24
952487,35,Ille-et-Vilaine,"MULTIPOLYGON (((-2.12371 48.60441, -2.14142 48...",1,LAURENT,1999,35,3
6439,76,Seine-Maritime,"POLYGON ((1.38155 50.06577, 1.40926 50.05707, ...",1,ABDOULAYE,1987,76,4

In [25]:
grouped = names.groupby(['dpt', 'preusuel', 'sexe'], as_index=False).sum()
grouped = depts.merge(grouped, how='right', left_on='code', right_on='dpt') # Add geometry data back in
grouped

TypeError: agg function failed [how->sum,dtype->geometry]

In [12]:
population = alt.Chart(baby_names, width=1200, height=500).mark_bar().encode(
    x=alt.X('annais:T', bin=alt.Bin(maxbins=60)),
    y='sum(nombre):Q',
)

population

alt.Chart(...)

In [16]:
alt.Chart(baby_names).mark_line().encode(
    x='annais:T', # <<
    y='nombre:Q',
)

alt.Chart(...)